service:
    MAPPER:
        mapping-enabled: false
orchestration:
    Sl-Or: {}
    ESCAPE-SERVICE:
        virtualizer_type: SINGLE
adaptation:
    CALLBACK:
        address: 127.0.0.1
        port: 9000
        timeout: 5
    DOV:
        # Generate unique ID for every nodes collected from domains
        ENSURE-UNIQUE-BiSBiS-ID: on
        # Generate unique ID for every NF nodes as well
        ENSURE-UNIQUE-VNF-ID: on
        # Enable REMERGE strategy for updating DoV instead of partial update
        USE-REMERGE-UPDATE-STRATEGY: true
        # Use status field to track component deployment instead of merging
        USE-STATUS-BASED-UPDATE: false
        # Update the global topology in one step instead of per-domains
        ONE-STEP-UPDATE: false
    MANAGERS:
    - MININET
    - OPENSTACK
    - DOCKER-1
    - UN
    - RYU
    MININET:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: MININET
        diff: true
        poll: on
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: ro/mininet
                url: http://127.0.0.1:8899
            CALLBACK:
                enabled: true
    OPENSTACK:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: OPENSTACK
        diff: true
        poll: on
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: ro/os
                url: http://127.0.0.1:8899
                timeout: 1
            CALLBACK:
                enabled: true
    DOCKER-1:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: DOCKER-1
        diff: true
        poll: on
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: ro/docker1
                url: http://127.0.0.1:8899
            CALLBACK:
                enabled: true
    UN:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: UN
        diff: true
        poll: on
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: ro/un
                url: http://127.0.0.1:8899
            CALLBACK:
                enabled: true
    RYU:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: RYU
        diff: true
        poll: on
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: ro/ryu
                url: http://127.0.0.1:8899
            CALLBACK:
                enabled: true
