REST-API:
  host: 0.0.0.0
  port: 8888
  prefix: escape
  auth_user: 5gex
  auth_secret: "58d5a4e7d09b649503d05a6789dfe292"
service:
    MAPPER:
        mapping-enabled: false
orchestration:
    Sl-Or:
        virtualizer_type: SINGLE
    ESCAPE-SERVICE:
        virtualizer_type: SINGLE
adaptation:
    CLEAR-DOMAINS-AFTER-SHUTDOWN: true
    MANAGERS:
    - MININET
    - OPENSTACK
    - DOCKER-1
    - DOCKER-2
    - UN
    - RYU
    MININET:
        module: escape.adapt.managers
        class: BasicDomainManager
        domain_name: MININET
        adapters:
            TOPOLOGY:
                module: escape.adapt.adapters
                class: VirtualizerBasedStaticFileAdapter
                path: examples/dummy/00-mininet.xml
                diff: true
    OPENSTACK:
        module: escape.adapt.managers
        class: BasicDomainManager
        domain_name: OPENSTACK
        adapters:
            TOPOLOGY:
                module: escape.adapt.adapters
                class: VirtualizerBasedStaticFileAdapter
                path: examples/dummy/00-openstack.xml
                diff: true
    DOCKER-1:
        module: escape.adapt.managers
        class: BasicDomainManager
        domain_name: DOCKER-1
        adapters:
            TOPOLOGY:
                module: escape.adapt.adapters
                class: VirtualizerBasedStaticFileAdapter
                path: examples/dummy/00-docker1.xml
                diff: true
    DOCKER-2:
        module: escape.adapt.managers
        class: BasicDomainManager
        domain_name: DOCKER-2
        adapters:
            TOPOLOGY:
                module: escape.adapt.adapters
                class: VirtualizerBasedStaticFileAdapter
                path: examples/dummy/00-docker2.xml
                diff: true
    UN:
        module: escape.adapt.managers
        class: BasicDomainManager
        domain_name: UN
        adapters:
            TOPOLOGY:
                module: escape.adapt.adapters
                class: VirtualizerBasedStaticFileAdapter
                path: examples/dummy/00-un.xml
                diff: true
    RYU:
        module: escape.adapt.managers
        class: BasicDomainManager
        domain_name: RYU
        adapters:
            TOPOLOGY:
                module: escape.adapt.adapters
                class: VirtualizerBasedStaticFileAdapter
                path: examples/dummy/00-ryu-sdn.xml
                diff: true
