service:
    MAPPER:
        mapping-enabled: false
orchestration:
    Sl-Or:
        virtualizer_type: SINGLE
    ESCAPE-SERVICE:
        virtualizer_type: SINGLE
adaptation:
    MANAGERS:
    - MININET
    - OPENSTACK
    - DOCKER-1
    - UN
    - RYU
    MININET:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: MININET
        diff: true
        poll: true
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: /ro/mininet
                url: http://127.0.0.1:8899
                features:
                  antiaffinity: yes
    OPENSTACK:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: OPENSTACK
        diff: true
        poll: true
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: ro/os
                url: http://127.0.0.1:8899
                timeout: 1
    DOCKER-1:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: DOCKER-1
        diff: true
        poll: true
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: /ro/docker1
                url: http://127.0.0.1:8899
    UN:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: UN
        diff: true
        poll: true
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: ro/un
                url: http://127.0.0.1:8899
    RYU:
        module: escape.adapt.managers
        class: UnifyDomainManager
        domain_name: RYU
        diff: true
        poll: true
        adapters:
            REMOTE:
                module: escape.adapt.adapters
                class: UnifyRESTAdapter
                prefix: /ro/ryu
                url: http://127.0.0.1:8899
infrastructure: {}
visualization:
    url: http://192.168.1.206:2222
    rpc: /notification
